export const mockData = {
  accounts: [
    {
      id: "1",
      name: "Main Trading Account",
      balance: 10245.0,
      broker: "Interactive Brokers",
      image: "",
    },
    {
      id: "2",
      name: "Demo Account",
      balance: 50000.0,
      broker: "MetaTrader 5",
      image: "",
    },
    {
      id: "3",
      name: "Swing Trading",
      balance: 25680.75,
      broker: "TD Ameritrade",
      image: "",
    },
    {
      id: "4",
      name: "Scalping Account",
      balance: 5120.3,
      broker: "TradeStation",
      image: "",
    },
    {
      id: "5",
      name: "Long-term Portfolio",
      balance: 75450.25,
      broker: "Fidelity",
      image: "",
    },
  ],
  trades: [
    {
      id: "T001",
      date: "2024-03-15T10:30:00Z",
      symbol: "EUR/USD",
      direction: "Long" as const,
      projectedEntry: 1.0875,
      projectedSL: 1.085,
      projectedTP: 1.092,
      actualEntry: 1.0875,
      actualExit: 1.092,
      didHitTP: true,
      actualPL: 45.0,
      maxPossiblePL: 45.0,
      efficiency: 100,
      notes: "Perfect execution, hit TP as planned",
      accountId: "1",
    },
    {
      id: "T002",
      date: "2024-03-15T14:15:00Z",
      symbol: "BTC/USD",
      direction: "Short" as const,
      projectedEntry: 43000.0,
      projectedSL: 43200.0,
      projectedTP: 42500.0,
      actualEntry: 43000.0,
      actualExit: null,
      didHitTP: null,
      actualPL: -120.5,
      maxPossiblePL: 500.0,
      efficiency: -24.1,
      notes: "Still running, moved SL to BE",
      accountId: "2",
    },
    {
      id: "T003",
      date: "2024-03-14T09:45:00Z",
      symbol: "XAU/USD",
      direction: "Long" as const,
      projectedEntry: 1942.3,
      projectedSL: 1938.0,
      projectedTP: 1950.0,
      actualEntry: 1942.3,
      actualExit: 1938.6,
      didHitTP: false,
      actualPL: -3.7,
      maxPossiblePL: 7.7,
      efficiency: -48.1,
      notes: "Stopped out, market reversed after news",
      accountId: "3",
    },
    {
      id: "T004",
      date: "2024-03-14T16:20:00Z",
      symbol: "USD/JPY",
      direction: "Short" as const,
      projectedEntry: 149.2,
      projectedSL: 149.5,
      projectedTP: 148.5,
      actualEntry: 149.2,
      actualExit: 149.9,
      didHitTP: false,
      actualPL: 70.0,
      maxPossiblePL: 70.0,
      efficiency: 100,
      notes: "Closed manually before NFP",
      accountId: "4",
    },
    {
      id: "T005",
      date: "2024-03-13T11:10:00Z",
      symbol: "ETH/USD",
      direction: "Long" as const,
      projectedEntry: 3200.0,
      projectedSL: 3180.0,
      projectedTP: 3250.0,
      actualEntry: 3200.0,
      actualExit: null,
      didHitTP: null,
      actualPL: 85.3,
      maxPossiblePL: 50.0,
      efficiency: 170.6,
      notes: "Running trade, moved SL to +1R",
      accountId: "5",
    },
  ],
  performance: {
    metrics: {
      winRate: 75,
      averageRR: 60,
      tradeFrequency: 80,
      plConsistency: 70,
      holdingTime: 50,
      executionQuality: 85,
      emotionalControl: 90,
      monthlyChange: 5.2,
      period: "January - June 2024",
    },
    overview: {
      totalTrades: 156,
      winRate: "68.5%",
      averageRR: "1.8",
      totalPL: 12450.75,
      monthlyPL: 3250.25,
      openTrades: 3,
      bestTrade: 850.0,
      worstTrade: -320.5,
    },
  },
};

// Helper function to get recent trades with account details
export function getRecentTrades() {
  return mockData.trades
    .slice(0, 5)
    .map((trade) => {
      const account = mockData.accounts.find(
        (acc) => acc.id === trade.accountId
      );
      return {
        ...trade,
        account: account?.name || "Unknown Account",
        accountValue: account?.balance || 0,
        image: account?.image,
      };
    })
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}
